const oracle = require('oracledb');
const Schema = oracle.Schema;

const userSchema = new Schema({
    id: {type:Number},//ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
    email: {type:String},//email VARCHAR2(255) NOT NULL
    uname: {type:String},//uname VARCHAR2(50) NOT NULL
    pw: {type:String},//pw VARCHAR2(255) NOT NULL
    feeder: {type:Boolean},//feeder NUMBER(1)
    trapper: {type:Boolean},//trapper NUMBER(1)
    admin: {type:Boolean} //admin NUMBER(1)
});

const catSchema = new Schema({
    catId: {type:Number},//ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
    cname: {type:String},//name VARCHAR2(255) NOT NULL
    age: {type:Number},//age NUMBER(3) NOT NULL
    calias:  {type:Array},
    geographical_area: {type:String},
    microchipped: {type:Boolean},
    hlength: {type:String},
    photos: {type:Array}, 
    gender: {type:String}, //F, M
    vaccinations: {type:String}, 
    age: {type:Number}, //maybe there should be a kitten/adult/senior option
    chipID: {type:String},
    eartip: {type:Boolean},
    feederID: {type:Number}
});

const Users = oracle.model('Users', userSchema, 'Caretakers');
const Cats = oracle.model('Cats', catSchema, 'Cats');